baseURL = 'https://spyke.space/'
locale = 'en-us'
title = 'Spyke Space'
theme= 'hugo-theme-stack'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "About Me"
url = "/about/"
weight = 25

[params.sidebar]
emoji = "✨"
subtitle = "A place to wonder."
avatar = "/img/avatar.png"

[params.widgets]
homepage = []
page = []

[params.comments]
enabled = false
provider = "giscus"

[params.comments.giscus]
repo = "awesomespyke/field-notes"
repoID = "R_kgDOSuaJxA"
category = "General"
categoryID = "DIC_kwDOSuaJxM4C_KSA"

mapping = "pathname"
strict = "0"
reactionsEnabled = "0"
emitMetadata = "0"
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "en"

[params.article.list]
showTags = false